### ISSUE TITLE
train process

### ISSUE THREAD

**Issue by lss11005** [LyricZhao/ASC19-FaceSR-SICNN#2]
Is there some functions lost?
when I want to run ref.py so as to train a new model, how to load dataset, the 10th "from dataset import TrainDatasetFromFolder, TestDatasetFromFolder" in ref.py is missing
Also "from score import evaluate" and "import net_sphere" show that module is not found.

**Comment by Awenjie10** [comment]
Same issue, Had you solve the problem? @lss11005  @LyricZhao

**Comment by LyricZhao** [comment]
Sorry for the confusing. It's a repo for a SR task of a competition. We do reproduce the all the training with PyTorch at first (but we lost the code now), and have optimized for the metric of the competition, which is pretty different with the original paper. Currently I'm a junior student of CS with lots of homework and won't maintain the repo any more. I'm sorry that you may can just take the code of this repo as a reference.
